[[redirects]]
  from = "/application-test-v1.1"
  to = "http://68.178.162.203:8080/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"